import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}), { virtual: true });
vi.mock("@/lib/driver-ranking/ranking-config-service", async () => { const score = await import("@/lib/driver-ranking/driver-ranking-score"); return { loadEffectiveRankingConfig: async () => score.RECOMMENDED_CONFIG }; });
import Employees from "@/lib/models/SymxEmployee";
import Routes from "@/lib/models/SYMXRoute";
import RouteTypes from "@/lib/models/RouteType";
import Writeups from "@/lib/models/Writeup";
import WeeklyOverview from "@/lib/models/SymxDeliveryExcellence";
import AmazonReportImport from "@/lib/models/AmazonReportImport";
import { currentAmazonWeek, loadDriverRankingData, parseRouteDurationMinutes, rankingPeriod, type DriverRankingRow } from "@/lib/driver-ranking/driver-ranking-data";
import { defaultDirection, sortDrivers, type DriverSortKey } from "@/lib/driver-ranking/driver-ranking-sort";
import { effectiveDriverEfficiency } from "@/lib/dispatching/driver-efficiency";
import { amazonWeeklyMetrics, weeklyMetricValue } from "@/lib/driver-ranking/amazon-weekly-summary";
import { efficiencyDistribution, getEfficiencyPerformanceState, getOperationalPerformanceState, getWeeklyMetricPerformanceState } from "@/lib/driver-ranking/performance-colors";

const site = "507f1f77bcf86cd799439011", employee = "607f1f77bcf86cd799439011", importId = "707f1f77bcf86cd799439099";
const routeType = "707f1f77bcf86cd799439011", calloutType = "707f1f77bcf86cd799439012", offType = "707f1f77bcf86cd799439013";
const rows = (value: any) => ({ lean: async () => value });
beforeEach(() => {
  vi.useFakeTimers(); vi.setSystemTime(new Date("2026-09-02T12:00:00Z"));
  vi.spyOn(Employees, "find").mockReturnValue(rows([{ _id: employee, firstName: "Test", lastName: "Driver", transporterId: " da-1 ", profileImage: "profile.jpg", primarySiteId: site, status: "Active" }, { _id: "607f1f77bcf86cd799439012", firstName: "No", lastName: "Data", transporterId: "DA-2", primarySiteId: site, status: "Active" }, { _id: "607f1f77bcf86cd799439013", firstName: "No", lastName: "Score", transporterId: "DA-3", primarySiteId: site, status: "Active" }]) as any);
  vi.spyOn(Routes, "find").mockReturnValue(rows([{ transporterId: "DA-1", date: "2026-09-01", typeId: routeType, routeNumber: "CX1", driverEfficiency: 90, stopCount: 100, packageCount: 120 }, { transporterId: "DA-1", date: "2026-09-02", typeId: calloutType, routeNumber: "", driverEfficiency: 0, stopCount: 0, packageCount: 0 }, { transporterId: "DA-1", date: "2026-09-03", typeId: offType, routeNumber: "BAD", driverEfficiency: 99, stopCount: 50, packageCount: 60 }]) as any);
  vi.spyOn(RouteTypes, "find").mockReturnValue(rows([{ _id: routeType, name: "Route" }, { _id: calloutType, name: "Call Out" }, { _id: offType, name: "OFF" }]) as any);
  vi.spyOn(Writeups, "find").mockReturnValue(rows([{ employeeId: employee, transporterId: "", incidentDate: "2026-09-02", categoryLabel: "Quality", status: "closed" }]) as any);
  vi.spyOn(WeeklyOverview, "find").mockReturnValue(rows([{ transporterId: " da-1 ", sourceImportIds: [importId], overallScore: 99.47, overallStanding: "Platinum", packagesDelivered: 1047, ficoMetric: null, speedingEventRate: 0, cdfDpmo: 633, cdfDpmoTier: "Platinum", cdfDpmoScore: 86.36, pod: 98.5, psb: null, speedingEventRateWeightApplied: 13.2 }, { transporterId: "DA-2", sourceImportIds: [importId], overallScore: 80 }]) as any);
  vi.spyOn(AmazonReportImport, "find").mockReturnValue(rows([{ _id: importId }]) as any);
  vi.spyOn(Routes, "distinct").mockResolvedValue(["2026-W36"] as never); vi.spyOn(WeeklyOverview, "distinct").mockResolvedValue(["2026-W35"] as never);
});
afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks(); });

describe("Driver ranking data foundation", () => {
  it("uses Los Angeles business dates and supports custom ranges", () => { expect(currentAmazonWeek(new Date("2026-09-06T06:30:00Z"))).toBe("2026-W36"); expect(rankingPeriod({ week: "2026-W36" })).toMatchObject({ yearWeek: "2026-W36" }); expect(rankingPeriod({ startDate: "2026-09-01", endDate: "2026-09-03" })).toEqual({ startDate: "2026-09-01", endDate: "2026-09-03", yearWeek: null }); });
  it("batches sources, joins successful weekly provenance, and excludes Call Out/OFF routes", async () => { const result = await loadDriverRankingData(site, { week: "2026-W36" }), driver = result.drivers.find(row => row.transporterId === "DA-1")!; expect(driver).toMatchObject({ profileImage: "profile.jpg", amazonWeekly: { overallScore: 99.47, overallStanding: "Platinum", packagesDelivered: 1047, safety: { fico: { value: null }, speeding: { value: 0 } }, quality: { cdf: { value: 633 }, pod: { value: 98.5 }, psb: { value: null } } }, efficiency: { average: 90, routeCount: 1 }, routes: { count: 1 }, production: { stops: 100, symxPackages: 120 }, attendance: { callOutCount: 1 }, writeUps: { count: 1 } }); expect(result.scorecardImported).toBe(true); expect(Employees.find).toHaveBeenCalledTimes(1); expect(Routes.find).toHaveBeenCalledTimes(1); expect(WeeklyOverview.find).toHaveBeenCalledTimes(1); expect(Writeups.find).toHaveBeenCalledTimes(1); });
  it("requires selected-week delivery activity in addition to a valid scorecard", async () => { const result = await loadDriverRankingData(site, { week: "2026-W36" }); expect(result.drivers.map(row => row.transporterId)).toEqual(["DA-1"]); expect(result.drivers[0]).toMatchObject({ deliveryDays: 1, amazonWeekly: { overallScore: 99.47 } }); expect(result.drivers.some(row => row.transporterId === "DA-2")).toBe(false); expect(result.drivers.some(row => row.transporterId === "DA-3")).toBe(false); });
  it("counts distinct qualifying delivery dates without double-counting routes", async () => { vi.spyOn(Routes, "find").mockReturnValue(rows([{ transporterId: "DA-1", date: "2026-09-01", typeId: routeType, routeNumber: "R1" }, { transporterId: "DA-1", date: "2026-09-01", typeId: routeType, routeNumber: "R2" }, { transporterId: "DA-1", date: "2026-09-02", typeId: routeType, routeNumber: "R3" }, { transporterId: "DA-1", date: "2026-09-03", typeId: calloutType, routeNumber: "BAD" }, { transporterId: "DA-1", date: "2026-09-04", typeId: offType, routeNumber: "BAD" }]) as any); const driver = (await loadDriverRankingData(site, { week: "2026-W36" })).drivers[0]; expect(driver.deliveryDays).toBe(2); });

  it("counts package volume only on qualifying delivery routes", async () => { vi.spyOn(Routes, "find").mockReturnValue(rows([{ transporterId: "DA-1", date: "2026-09-01", typeId: routeType, routeNumber: "R1", packageCount: 120 }, { transporterId: "DA-1", date: "2026-09-02", typeId: routeType, routeNumber: "R2", packageCount: 150 }, { transporterId: "DA-1", date: "2026-09-03", typeId: calloutType, routeNumber: "BAD", packageCount: 500 }, { transporterId: "DA-1", date: "2026-09-04", typeId: offType, routeNumber: "BAD", packageCount: 600 }]) as any); const driver = (await loadDriverRankingData(site, { week: "2026-W36" })).drivers[0]; expect(driver.workload.qualifyingDeliveryPackages).toBe(270); expect(driver.score?.packagesPerDeliveryDay).toBe(135); });
  it("parses routeDuration as a duration, including totals beyond a clock day", () => { expect(parseRouteDurationMinutes("6:56")).toBe(416); expect(parseRouteDurationMinutes("40:35")).toBe(2435); expect(parseRouteDurationMinutes("6:30:30")).toBe(390.5); expect(parseRouteDurationMinutes("6:75")).toBeNull(); expect(parseRouteDurationMinutes(6.5)).toBeNull(); });
  it("aggregates valid workload measurements and exposes partial coverage", async () => { vi.spyOn(Routes, "find").mockReturnValue(rows([{ transporterId: "DA-1", date: "2026-09-01", typeId: routeType, routeNumber: "R1", routeDuration: "6:00", stopCount: 100, packageCount: 0 }, { transporterId: "DA-1", date: "2026-09-02", typeId: routeType, routeNumber: "R2", routeDuration: "7:00", stopCount: 0, packageCount: 200 }, { transporterId: "DA-1", date: "2026-09-02", typeId: routeType, routeNumber: "R3", routeDuration: "", stopCount: undefined, packageCount: undefined }]) as any); const driver = (await loadDriverRankingData(site, { week: "2026-W36" })).drivers[0]; expect(driver).toMatchObject({ deliveryDays: 2, routes: { count: 3 }, workload: { totalPlannedRouteMinutes: 780, averagePlannedRouteMinutes: 390, plannedDurationRouteCount: 2, missingPlannedDurationRouteCount: 1, averageStopsPerRoute: 50, stopsRouteCount: 2, missingStopsRouteCount: 1, averagePackagesPerRoute: 100, packagesRouteCount: 2, missingPackagesRouteCount: 1 }, production: { stops: 100, symxPackages: 200 } }); });
  it("returns a clean empty dataset when no successful Weekly Scorecard exists", async () => { vi.spyOn(AmazonReportImport, "find").mockReturnValue(rows([]) as any); const result = await loadDriverRankingData(site, { week: "2026-W36" }); expect(result).toMatchObject({ scorecardImported: false, drivers: [] }); });
  it("includes an inactive employee in a historical scored week only with selected-site route evidence", async () => { vi.spyOn(Employees, "find").mockReturnValue(rows([{ _id: employee, firstName: "Former", lastName: "Driver", transporterId: "DA-1", primarySiteId: site, status: "Inactive" }, { _id: "607f1f77bcf86cd799439012", firstName: "No", lastName: "Activity", transporterId: "DA-2", primarySiteId: site, status: "Inactive" }]) as any); const result = await loadDriverRankingData(site, { week: "2026-W35" }); expect(result.drivers.map(row => row.transporterId)).toEqual(["DA-1"]); });
  it("keeps current-week population restricted to active drivers at the current site", async () => { vi.spyOn(Employees, "find").mockReturnValue(rows([{ _id: employee, firstName: "Inactive", lastName: "Driver", transporterId: "DA-1", primarySiteId: site, status: "Inactive" }]) as any); expect((await loadDriverRankingData(site, { week: "2026-W36" })).drivers).toEqual([]); });
  it("averages calculated efficiencies from qualifying routes only", async () => { vi.spyOn(Routes, "find").mockReturnValue(rows([{ transporterId: "DA-1", date: "2026-09-01", typeId: routeType, routeNumber: "R1", plannedFirstStop: "10:00", plannedLastStop: "18:00", actualFirstStop: "10:00", actualLastStop: "18:00", stopCount: 160 }, { transporterId: "DA-1", date: "2026-09-02", typeId: routeType, routeNumber: "R2", plannedFirstStop: "10:00", plannedLastStop: "18:00", actualFirstStop: "10:00", actualLastStop: "20:00", stopCount: 160 }, { transporterId: "DA-1", date: "2026-09-03", typeId: calloutType, routeNumber: "R3", driverEfficiency: 99 }]) as any); const driver = (await loadDriverRankingData(site, { week: "2026-W36" })).drivers.find(row => row.transporterId === "DA-1")!; expect(driver.efficiency).toEqual({ average: 90, routeCount: 2 }); expect(driver.deliveryDays).toBe(2); });
});

describe("Shared driver efficiency calculation", () => {
  const route = { plannedFirstStop: "10:00", plannedLastStop: "18:00", actualFirstStop: "10:00", actualLastStop: "18:00", stopCount: 160, stopsRescued: 0 };
  it("matches the existing planned/actual duration calculation", () => { expect(effectiveDriverEfficiency(route)).toBe(100); });
  it("preserves the existing rescue-minute adjustment", () => { expect(effectiveDriverEfficiency({ ...route, stopsRescued: 20 })).toBe(89); });
  it("uses a valid stored value when timing inputs are missing or invalid", () => { expect(effectiveDriverEfficiency({ driverEfficiency: 92 })).toBe(92); expect(effectiveDriverEfficiency({ ...route, actualLastStop: "09:00", driverEfficiency: 91 })).toBe(91); });
  it("returns null when neither calculation inputs nor stored efficiency are valid", () => { expect(effectiveDriverEfficiency({})).toBeNull(); expect(effectiveDriverEfficiency({ ...route, actualLastStop: "09:00", driverEfficiency: 0 })).toBeNull(); });
});

describe("Amazon Weekly row metrics", () => {
  const weekly = { safety: { fico: { value: 800, tier: "Platinum" }, speeding: { value: 0, tier: "Platinum" }, seatbelt: { value: 0, tier: "Gold" }, distractions: { value: 0, tier: "Silver" }, signSignal: { value: 0, tier: "Bronze" }, followingDistance: { value: null, tier: "Platinum" } }, quality: { cdf: { value: 1456, score: 60.49, tier: "Bronze" }, ced: { value: 3, score: 75, tier: "Gold" }, deliveryCompletion: { value: 725.6, score: 92.74, tier: "Gold" }, dsb: { value: 0, score: 100, tier: "Platinum" }, pod: { value: 99.1, score: 89.11, tier: "Silver" }, psb: { value: 0, score: 100, tier: "Platinum" } } } as any;
  it("shows unchanged raw values with tier-derived states", () => { expect(amazonWeeklyMetrics(weekly)).toEqual([{ label: "CDF", value: "1,456 DPMO", state: "attention" }, { label: "DSB", value: "0", state: "top" }, { label: "DC", value: "725.6 DPMO", state: "good" }, { label: "POD", value: "99.1%", state: "good" }, { label: "PSB", value: "0", state: "top" }, { label: "Speeding", value: "0", state: "top" }, { label: "Seatbelt", value: "0", state: "good" }, { label: "Distractions", value: "0", state: "good" }, { label: "Sign / Signal", value: "0", state: "attention" }, { label: "Following Distance", value: "N/A", state: "missing" }]); });
  it("preserves zero and uses N/A only for missing values", () => { expect(weeklyMetricValue(0)).toBe("0"); expect(weeklyMetricValue(null)).toBe("N/A"); expect(weeklyMetricValue(undefined)).toBe("N/A"); });
  it("omits CED and FICO from the normal weekly metric presentation", () => { expect(amazonWeeklyMetrics(weekly).map(metric => metric.label)).not.toEqual(expect.arrayContaining(["CED", "FICO"])); });
});

describe("Driver ranking performance colors", () => {
  it("maps Amazon tiers to blue/top, green/good, red/attention, and gray/missing", () => { expect(getWeeklyMetricPerformanceState(0, "Platinum")).toBe("top"); expect(getWeeklyMetricPerformanceState(1, "Gold")).toBe("good"); expect(getWeeklyMetricPerformanceState(1, "Silver")).toBe("good"); expect(getWeeklyMetricPerformanceState(1, "Bronze")).toBe("attention"); expect(getWeeklyMetricPerformanceState(null, "Bronze")).toBe("missing"); expect(getWeeklyMetricPerformanceState(0, null)).toBe("missing"); });
  it("uses selected-week quartiles for efficiency without creating points", () => { const distribution = efficiencyDistribution([70, 80, 90, 100, null]); expect(getEfficiencyPerformanceState(100, distribution)).toBe("top"); expect(getEfficiencyPerformanceState(90, distribution)).toBe("good"); expect(getEfficiencyPerformanceState(70, distribution)).toBe("attention"); expect(getEfficiencyPerformanceState(null, distribution)).toBe("missing"); });
  it("colors zero call-outs/write-ups as top and one-plus as attention", () => { expect(getOperationalPerformanceState(0)).toBe("top"); expect(getOperationalPerformanceState(1)).toBe("attention"); expect(getOperationalPerformanceState(null)).toBe("missing"); });
});

describe("Driver ranking sorting", () => {
  const driver = (name: string, value: number | null): DriverRankingRow => ({ driverId: name, transporterId: name, name, profileImage: null, siteId: site, period: { startDate: "", endDate: "", yearWeek: "2026-W36" }, amazonWeekly: value === null ? null : { overallScore: value, overallStanding: null, packagesDelivered: null, safety: {} as any, quality: {} as any, sourceWeights: {} as any }, efficiency: { average: value, routeCount: 0 }, deliveryDays: 1, routes: { count: value as number, trainingCount: 0, rescueOnlyCount: 0 }, workload: {} as any, production: { stops: value, symxPackages: value }, attendance: { callOutCount: value as number, callOutDates: [] }, writeUps: { count: value as number, records: [] } });
  it.each(["amazon", "efficiency", "routes", "stops", "packages", "callouts", "writeups"] as DriverSortKey[])("sorts %s both directions with null last", key => { const input = [driver("Low", 1), driver("Missing", null), driver("High", 9)]; expect(sortDrivers(input, key, "desc").map(row => row.name)).toEqual(["High", "Low", "Missing"]); expect(sortDrivers(input, key, "asc").map(row => row.name)).toEqual(["Low", "High", "Missing"]); });
  it("sorts official rank best-first by default and reverses without rewriting ranks", () => { const input = [driver("Third", 3), driver("First", 1), driver("Second", 2)]; input.forEach((row, index) => { row.score = { rank: [3, 1, 2][index] } as any; }); expect(defaultDirection("rank")).toBe("desc"); expect(sortDrivers(input, "rank", "desc").map(row => [row.name, row.score?.rank])).toEqual([["First", 1], ["Second", 2], ["Third", 3]]); expect(sortDrivers(input, "rank", "asc").map(row => [row.name, row.score?.rank])).toEqual([["Third", 3], ["Second", 2], ["First", 1]]); });
  it("sorts displayed names case-insensitively in both directions without rewriting ranks", () => { const input = [driver("miles", 3), driver("Aliyah", 1), driver("ernesto", 2)]; input.forEach((row, index) => { row.score = { rank: [23, 2, 46][index] } as any; }); expect(defaultDirection("name")).toBe("asc"); expect(sortDrivers(input, "name", "asc").map(row => [row.name, row.score?.rank])).toEqual([["Aliyah", 2], ["ernesto", 46], ["miles", 23]]); expect(sortDrivers(input, "name", "desc").map(row => row.name)).toEqual(["miles", "ernesto", "Aliyah"]); });
  it("sorts average planned route minutes numerically with missing data last and preserves rank", () => { const input = [driver("Short", 1), driver("Missing", 2), driver("Long", 3)]; input[0].workload.averagePlannedRouteMinutes = 360; input[1].workload.averagePlannedRouteMinutes = null; input[2].workload.averagePlannedRouteMinutes = 492; input.forEach((row, index) => { row.score = { rank: [8, 2, 14][index] } as any; }); expect(defaultDirection("averageRoute")).toBe("desc"); expect(sortDrivers(input, "averageRoute", "desc").map(row => [row.name, row.score?.rank])).toEqual([["Long", 14], ["Short", 8], ["Missing", 2]]); expect(sortDrivers(input, "averageRoute", "asc").map(row => row.name)).toEqual(["Short", "Long", "Missing"]); });
  it("sorts delivery days both directions without rewriting official rank", () => { const input = [driver("Two", 1), driver("Five", 2), driver("One", 3)]; [2, 5, 1].forEach((days, index) => { input[index].deliveryDays = days; input[index].score = { rank: [11, 4, 20][index] } as any; }); expect(defaultDirection("days")).toBe("desc"); expect(sortDrivers(input, "days", "desc").map(row => [row.name, row.score?.rank])).toEqual([["Five", 4], ["Two", 11], ["One", 20]]); expect(sortDrivers(input, "days", "asc").map(row => row.name)).toEqual(["One", "Two", "Five"]); });
  it("uses intuitive defaults", () => { expect(defaultDirection("amazon")).toBe("desc"); expect(defaultDirection("efficiency")).toBe("desc"); expect(defaultDirection("callouts")).toBe("asc"); expect(defaultDirection("writeups")).toBe("asc"); });
});
