import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { driverRankingCsv, driverRankingExportRows, driverRankingFilename, DRIVER_RANKING_EXPORT_HEADERS } from "@/lib/driver-ranking/driver-ranking-export";
import { RECOMMENDED_CONFIG, RANKING_METRICS } from "@/lib/driver-ranking/driver-ranking-score";
import type { DriverRankingResult, DriverRankingRow } from "@/lib/driver-ranking/driver-ranking-data";

const metric = (value: number | null, score: number | null) => ({ value, score, tier: null });
const driver = (name: string, rank: number): DriverRankingRow => ({
  driverId: String(rank), transporterId: `PRIVATE-${rank}`, name, profileImage: null, siteId: "site",
  period: { startDate: "2026-09-07", endDate: "2026-09-13", yearWeek: "2026-W37" }, deliveryDays: rank,
  amazonWeekly: { overallScore: 99, overallStanding: "Platinum", packagesDelivered: 100, safety: { fico: metric(800, 100), speeding: metric(0, 100), seatbelt: metric(null, null), distractions: metric(0, 100), signSignal: metric(0, 100), followingDistance: metric(0, 100) }, quality: { cdf: metric(1456, 60.49), ced: metric(0, 100), deliveryCompletion: metric(725.6, 92.74), dsb: metric(0, 100), pod: metric(99.1, 89.11), psb: metric(0, 100) }, sourceWeights: {} as any },
  efficiency: { average: 106.4, routeCount: 4 }, routes: { count: 4, trainingCount: 0, rescueOnlyCount: 0 }, workload: { totalPlannedRouteMinutes: 1968, averagePlannedRouteMinutes: 492, plannedDurationRouteCount: 4, missingPlannedDurationRouteCount: 0, averageStopsPerRoute: null, stopsRouteCount: 0, missingStopsRouteCount: 4, averagePackagesPerRoute: 296.75, packagesRouteCount: 4, missingPackagesRouteCount: 0 }, production: { stops: null, symxPackages: 1187 }, attendance: { callOutCount: 1, callOutDates: [] }, writeUps: { count: 0, records: [] },
  score: { rank, baseScore: 90, exposureAdjustedBase: 88, deliveryDays: rank, deliveryDaysScore: 35, qualifyingDeliveryPackages: null, packagesPerDeliveryDay: null, packagesPerDayPercentileScore: null, workloadScore: null, workloadContribution: 0, exposureConfidence: rank / 4, teamAverageBaseScore: 86, exposureAdjustment: -2, safetyScore: 90, safetySubtotal: 40, safetyWeight: 44, qualityScore: 90, qualitySubtotal: 32, qualityWeight: 38, efficiencyScore: 90, efficiencySubtotal: 18, efficiencyWeight: 18, availableWeight: 91, missingMetrics: ["seatbelt"], contributions: RANKING_METRICS.map(metricName => ({ metric: metricName, normalizedScore: 100, configuredWeight: RECOMMENDED_CONFIG.weights[metricName], effectiveWeight: RECOMMENDED_CONFIG.weights[metricName], contribution: RECOMMENDED_CONFIG.weights[metricName] })), callOutPenalty: 10, writeUpPenalty: 0, cedApplied: false, scoreBeforeCap: 78, finalScore: 78 },
});
const result: DriverRankingResult = { period: { startDate: "2026-09-07", endDate: "2026-09-13", yearWeek: "2026-W37" }, availableWeeks: ["2026-W37"], scorecardImported: true, config: RECOMMENDED_CONFIG, drivers: [driver("Alpha, Driver", 1), driver("Beta Driver", 2)] };

describe("driver ranking CSV export", () => {
  it("exports the complete official population with workload, rank, raw data, scores, weights, contributions, exposure, modifiers, and config", () => { const rows = driverRankingExportRows(result, "DFO2"); expect(rows).toHaveLength(2); expect(rows[0]).toMatchObject({ Rank: 1, "Driver Name": "Alpha, Driver", Week: "2026-W37", Site: "DFO2", "Delivery Days": 1, Routes: 4, "Total Planned Route Minutes": 1968, "Average Planned Route Minutes": 492, "Planned Duration Route Count": 4, "Missing Planned Duration Route Count": 0, "SYMX Packages": 1187, "Average Packages Per Route": 296.75, "CDF DPMO Raw": 1456, "CDF Amazon Score": 60.49, "CDF Weight": 11, "CDF Contribution": 11, "Exposure Adjusted Base Score": 88, "Call Outs": 1, "Call Out Deduction": 10, "CED Triggered": false, "Final Score": 78, "Full Confidence Delivery Days": null, "Exposure Curve": "0.35/0.55/0.7/0.82/1" }); });
  it("leaves missing values blank, emits valid escaped CSV, and excludes unnecessary identity fields", () => { const csv = driverRankingCsv(result, "DFO2"); expect(csv).toContain('1,"Alpha, Driver"'); expect(csv).not.toContain("PRIVATE-1"); expect(DRIVER_RANKING_EXPORT_HEADERS).not.toEqual(expect.arrayContaining(["Transporter ID", "Email", "Phone", "Address", "DOB"])); const row = driverRankingExportRows(result, "DFO2")[0]; expect(row.Stops).toBeNull(); expect(row["Seatbelt Raw"]).toBeNull(); });
  it("uses the requested site/week filename", () => { expect(driverRankingFilename("DFO2", "2026-W37")).toBe("SYMX_Driver_Rankings_DFO2_2026-W37.csv"); });
  it("has no duplicate workload headers and protects spreadsheet text formulas", () => { expect(new Set(DRIVER_RANKING_EXPORT_HEADERS).size).toBe(DRIVER_RANKING_EXPORT_HEADERS.length); const unsafe = { ...result, drivers: [{ ...result.drivers[0], name: "=FORMULA()" }] }; expect(driverRankingCsv(unsafe, "DFO2")).toContain("'=FORMULA()"); });
  it("downloads by selected week without sending client search or sort state", () => { const page = readFileSync("app/(protected)/driver-rankings/page.tsx", "utf8"); expect(page).toContain("/api/driver-rankings/export?week="); expect(page).not.toMatch(/driver-rankings\/export\?[^`]*search/); expect(page).not.toMatch(/driver-rankings\/export\?[^`]*sort/); });
});
