import type { DriverRankingRow } from "./driver-ranking-data";
export type DriverHistoryWeek={week:string;finalScore:number;rank:number;safetyScore:number|null;qualityScore:number|null;workloadScore:number|null;efficiency:number|null;deliveryDays:number;packagesPerDay:number|null;teamPackagesPerDay:number|null;callOuts:number;writeUps:number;metrics:Record<string,number|null>};
export type MetricRank={value:number|null;rank:number|null;tied:boolean}; export type DriverMetricRanks=Record<string,MetricRank>;
export type DriverHistoryReview={trend:"Improving"|"Stable"|"Declining"|"Not enough data";slope:number|null;rankMovement:number|null;bestArea:"Safety"|"Quality"|"Efficiency"|null;mainFocus:string;recurringIssues:{label:string;weeks:number}[];improvingAreas:string[];consistency:{strongWeeks:number;validWeeks:number;variation:"Stable"|"Moderate variation"|"High variation"|null};managerStatus:"Strong"|"Watch"|"Needs Coaching";streaks:Record<string,number>};
const mean=(values:(number|null)[])=>{const valid=values.filter((v):v is number=>typeof v==="number"&&Number.isFinite(v));return valid.length?valid.reduce((s,v)=>s+v,0)/valid.length:null;};
export function linearSlope(values:(number|null)[]){const p=values.map((value,index)=>({value,index})).filter((x):x is {value:number;index:number}=>typeof x.value==="number"&&Number.isFinite(x.value));if(p.length<3)return null;const xm=mean(p.map(x=>x.index))!,ym=mean(p.map(x=>x.value))!,d=p.reduce((s,x)=>s+(x.index-xm)**2,0);return d?p.reduce((s,x)=>s+(x.index-xm)*(x.value-ym),0)/d:null;}
const RULES=[["Following Distance","followingDistance","safety",false],["Speeding","speeding","safety",false],["Seatbelt","seatbelt","safety",false],["Distractions","distractions","safety",false],["Sign / Signal","signSignal","safety",false],["Delivery Completion","deliveryCompletion","quality",false],["CDF","cdf","quality",false],["DSB","dsb","quality",false],["PSB","psb","quality",false],["POD","pod","quality",true]] as const;
const streak=(rows:DriverHistoryWeek[],weeks:string[],test:(r:DriverHistoryWeek)=>boolean)=>{const map=new Map(rows.map(r=>[r.week,r]));let n=0;for(const w of [...weeks].sort().reverse()){const r=map.get(w);if(!r||!test(r))break;n++;}return n;};
export function summarizeDriverHistory(history:DriverHistoryWeek[],windowWeeks=history.map(r=>r.week)):DriverHistoryReview{const rows=[...history].sort((a,b)=>a.week.localeCompare(b.week)),slope=linearSlope(rows.map(r=>r.finalScore)),trend=slope===null?"Not enough data":slope>=.25?"Improving":slope<=-.25?"Declining":"Stable",rankMovement=rows.length<2?null:rows[0].rank-rows.at(-1)!.rank;
const areas=[["Safety",mean(rows.map(r=>r.safetyScore))],["Quality",mean(rows.map(r=>r.qualityScore))],["Efficiency",mean(rows.map(r=>r.efficiency))]] as const,valid=areas.filter((a):a is [typeof a[0],number]=>a[1]!==null),bestArea=valid.sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]||null;
const issues=RULES.map(([label,key,group,higher])=>({label,key,group,weeks:rows.filter(r=>{const v=r.metrics[key];return v!==null&&(higher?v<100:v>0)}).length})).filter(x=>x.weeks>=2).sort((a,b)=>b.weeks-a.weeks),recurringIssues=issues.slice(0,3).map(({label,weeks})=>({label,weeks})),improvingAreas:string[]=RULES.flatMap(([label,key,,higher])=>{const s=linearSlope(rows.map(r=>r.metrics[key]));return s!==null&&Math.abs(s)>=.25&&((higher&&s>0)||(!higher&&s<0))?[label]:[]}),effSlope=linearSlope(rows.map(r=>r.efficiency));if(effSlope!==null&&effSlope>=.25)improvingAreas.push("Efficiency");
const safetyIssue=issues.find(x=>x.group==="safety"),qualityIssue=issues.find(x=>x.group==="quality"),repeatCall=rows.filter(r=>r.callOuts>0).length>=2,repeatWrite=rows.filter(r=>r.writeUps>0).length>=2,mainFocus=safetyIssue?.label||qualityIssue?.label||(effSlope!==null&&effSlope<=-.25?"Efficiency":repeatWrite?"Write-Ups":repeatCall?"Call Outs":"Maintain Performance"),scores=rows.map(r=>r.finalScore),avg=mean(scores),sd=avg===null?null:Math.sqrt(scores.reduce((s,v)=>s+(v-avg)**2,0)/scores.length),variation=sd===null?null:sd<2?"Stable":sd<5?"Moderate variation":"High variation",managerStatus=safetyIssue||qualityIssue||trend==="Declining"||repeatWrite?"Needs Coaching":recurringIssues.length||mainFocus!=="Maintain Performance"||scores.filter(s=>s>=95).length<Math.ceil(scores.length/2)?"Watch":"Strong";
const zero=(key:string)=>(r:DriverHistoryWeek)=>r.metrics[key]===0,safetyClean=(r:DriverHistoryWeek)=>{const v=["speeding","seatbelt","distractions","signSignal","followingDistance"].map(k=>r.metrics[k]).filter((x):x is number=>x!==null);return v.length>0&&v.every(x=>x===0)};
const streaks={top10:streak(rows,windowWeeks,r=>r.rank<=10),top5:streak(rows,windowWeeks,r=>r.rank<=5),number1:streak(rows,windowWeeks,r=>r.rank===1),safety:streak(rows,windowWeeks,safetyClean),speeding:streak(rows,windowWeeks,zero("speeding")),seatbelt:streak(rows,windowWeeks,zero("seatbelt")),distractions:streak(rows,windowWeeks,zero("distractions")),signSignal:streak(rows,windowWeeks,zero("signSignal")),followingDistance:streak(rows,windowWeeks,zero("followingDistance")),quality95:streak(rows,windowWeeks,r=>r.qualityScore!==null&&r.qualityScore>=95),cdf:streak(rows,windowWeeks,zero("cdf")),dsb:streak(rows,windowWeeks,zero("dsb")),deliveryCompletion:streak(rows,windowWeeks,zero("deliveryCompletion")),pod:streak(rows,windowWeeks,r=>r.metrics.pod!==null&&r.metrics.pod>=99.5),psb:streak(rows,windowWeeks,zero("psb")),efficiency100:streak(rows,windowWeeks,r=>r.efficiency!==null&&r.efficiency>=100),packagesAboveAverage:streak(rows,windowWeeks,r=>r.packagesPerDay!==null&&r.teamPackagesPerDay!==null&&r.packagesPerDay>=r.teamPackagesPerDay),fiveDays:streak(rows,windowWeeks,r=>r.deliveryDays>=5)};
return{trend,slope,rankMovement,bestArea,mainFocus,recurringIssues,improvingAreas:[...new Set(improvingAreas)].slice(0,3),consistency:{strongWeeks:scores.filter(s=>s>=95).length,validWeeks:scores.length,variation},managerStatus,streaks};}
const metricRank=(drivers:DriverRankingRow[],selected:DriverRankingRow,read:(d:DriverRankingRow)=>number|null,higher=true):MetricRank=>{const value=read(selected);if(value===null||!Number.isFinite(value))return{value:null,rank:null,tied:false};const values=drivers.map(read).filter((v):v is number=>v!==null&&Number.isFinite(v)),better=values.filter(v=>higher?v>value:v<value).length,ties=values.filter(v=>v===value).length;return{value,rank:better+1,tied:ties>1}};
export function driverMetricRanks(drivers:DriverRankingRow[],id:string):DriverMetricRanks|null{const d=drivers.find(x=>x.transporterId===id);if(!d)return null;return{finalScore:metricRank(drivers,d,x=>x.score?.finalScore??null),safety:metricRank(drivers,d,x=>x.score?.safetyScore??null),quality:metricRank(drivers,d,x=>x.score?.qualityScore??null),efficiency:metricRank(drivers,d,x=>x.efficiency.average),workload:metricRank(drivers,d,x=>x.score?.workloadScore??null),packagesPerDay:metricRank(drivers,d,x=>x.score?.packagesPerDeliveryDay??null),cdf:metricRank(drivers,d,x=>x.amazonWeekly?.quality.cdf.value??null,false),dsb:metricRank(drivers,d,x=>x.amazonWeekly?.quality.dsb.value??null,false),deliveryCompletion:metricRank(drivers,d,x=>x.amazonWeekly?.quality.deliveryCompletion.value??null,false),pod:metricRank(drivers,d,x=>x.amazonWeekly?.quality.pod.value??null),psb:metricRank(drivers,d,x=>x.amazonWeekly?.quality.psb.value??null,false)}}
export function driverHistoryWeek(d:DriverRankingRow,teamPackagesPerDay:number|null=null):DriverHistoryWeek{const w=d.amazonWeekly;return{week:d.period.yearWeek||"",finalScore:d.score!.finalScore,rank:d.score!.rank,safetyScore:d.score!.safetyScore,qualityScore:d.score!.qualityScore,workloadScore:d.score!.workloadScore,efficiency:d.efficiency.average,deliveryDays:d.deliveryDays,packagesPerDay:d.score!.packagesPerDeliveryDay,teamPackagesPerDay,callOuts:d.attendance.callOutCount,writeUps:d.writeUps.count,metrics:{speeding:w?.safety.speeding.value??null,seatbelt:w?.safety.seatbelt.value??null,distractions:w?.safety.distractions.value??null,signSignal:w?.safety.signSignal.value??null,followingDistance:w?.safety.followingDistance.value??null,cdf:w?.quality.cdf.value??null,dsb:w?.quality.dsb.value??null,deliveryCompletion:w?.quality.deliveryCompletion.value??null,pod:w?.quality.pod.value??null,psb:w?.quality.psb.value??null}}}
